name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Set environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
          echo "PORT=3000"

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Get container ID
        id: get_container_id
        run: |
          echo "CONTAINER_ID=$(docker ps -qf 'name=blog_api')" >> $GITHUB_ENV

      - name: Run tests
        run: docker exec ${{ env.CONTAINER_ID }} npm test -- --verbose
      
